[package]
name = "calloop-dbus"
version = "0.1.0"
authors = ["Alexander Sieg <alex@xanderio.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calloop = "0.6"
dbus = "0.8"
log = "0.4"
